### PR TITLE
Add more options, fix error and use osd for gap update notice

### PR DESCRIPTION
**Pull request by qwreey75**
Changes
1. Fix extension disable error (occurred by my PR mistake, sorry about it!)
2. User can adjust TILING_SUCCESSIVE_TIMEOUT (keybinding iterating for adjust step)
image

### CODE REVIEW

**Comment by qwreey75** [comment]
Also now using Clutter.Timeout, which supports hooking actual actor update
This behavior allow animation look faster then sleeping just a lot

**Comment by qwreey75** [comment]
image
I also added a changing gap size keybinding increments option, now user can set how much percent will increase/decrease

**Comment by qwreey75** [comment]
image

Now when press gap size keybinding, it shows osd popup (aka sound dialog)

**Review by velitasali — APPROVED** [review]
Hey @qwreey75. These changes are awesome. I really appreciate the work you have done here. Thanks again :)

**Pull request merged**
