### PR TITLE
tiling: Allow multiple sizes with tile window to center

### PR DESCRIPTION
**Pull request by nushoin**
When we align to the center we want to change all 4 sides.

Fixes issue #18

### CODE REVIEW

**Comment by velitasali** [comment]
Hi. Thank you very much for working on this. It works, but I am wondering if we can preserve the behavior where the initial press tiles the window based on the full width and height of the workspace. Right now, it is based on half the size.

**Comment by nushoin** [comment]
That's obviously doable but will probably make the code less elegant. Considering that GNOME Shell has a built-in shortcut for maximizing a window, i.e. Super+Up, do we really need that?

**Comment by velitasali** [comment]
I agree that default GNOME shortcuts are effective for smaller displays, but I have a big monitor, and I almost always use `Super + Keypad 5` with gaps enabled to keep windows in my peripheral vision. To have smaller windows, I use` Super +  Keypad 7`, and then center them with `Super + Keypad 0`, which is similar to your proposal. For other times, I use the default shell shortcuts. It would be nice if we kept that behavior.

**Comment by nushoin** [comment]
Can you try now? I split the addition to 2 separate commits so that the last one is just a cleanup for readability. If you don't want it just don't pull it.

**Comment by nushoin** [comment]
Btw review will be easier per-commit since GitHub messes up the diff if you view it entirely.

**Comment by velitasali** [comment]
@nushoin Looks good. Thanks for this. Could you rebase the commits into a single one so that I can merge it?

**Comment by nushoin** [comment]
@velitasali done.

**Pull request merged**
